---
##############################################################################
# Copyright (c) 2018 AT&T Intellectual Property. All rights reserved.        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License.                   #
#                                                                            #
# You may obtain a copy of the License at                                    #
#       http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT  #
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.           #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
##############################################################################
blueprint:
  name: base
  sections: 
  - hw
  - os
  - networking
  - k8s
  - sds
  - sdn
  - vim
  # Any hardware some basic tests
  hw: &hw_base 
  -
    name: bios_version
    condition: true # something that can be evaluated to true of false
    what: /opt/akraino/validation/bios_version
    show_stopper: true # yes this is a show stopper
  os: &os_base
  - 
    name: os_version
    what: /path/os_version.robot
  networking: &networking
  - 
    name: pxe_networking_test
    what: /path/to/pxe_networking_test.test 
  -  
    name: routes_test
    what: /path/to/routes_test
  k8s: &k8s
    - 
      name: conformance
      what: /path/to/conformance.robot  
    -  
      name: e2e
      what: /path/to/e2e.robot
  k8s_networking: &k8s_networking
    - 
      name: node_connectivity
      what: /path/to/node_connectivity.robot  
    - 
      name: pod_connectivity
      what: /path/to/epod_connectivity.robot
  sds: &sds # software defined storage
    - 
      name: sds
      what: /path/to/sds.robot
  sdn: &sdn # software defined network
    - 
      name: sns
      what: /path/to/sds.robot
  vim: &vim # Virtual Infrastructure Manager 
    - 
      name: vim_basic
      what: /path/to/vim_basic.robot
